<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>C:\temp\ADSOLUSOL\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>C:\temp\ADSOLUSOL\bin\$(MSBuildProjectName)\</BaseOutputPath>

    <DefaultItemExcludes>
      $(DefaultItemExcludes);**\obj\**;**\bin\**
    </DefaultItemExcludes>
  </PropertyGroup>
</Project>