<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ADSOLUSOL.Domain\ADSOLUSOL.Domain.csproj" />
    <ProjectReference Include="..\..\src\ADSOLUSOL.Application\ADSOLUSOL.Application.csproj" />
    <ProjectReference Include="..\..\src\ADSOLUSOL.Infrastructure\ADSOLUSOL.Infrastructure.csproj" />
  </ItemGroup>
</Project>
