<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ADSOLUSOL.Domain\ADSOLUSOL.Domain.csproj" />
    <ProjectReference Include="..\ADSOLUSOL.Application\ADSOLUSOL.Application.csproj" />
    <ProjectReference Include="..\ADSOLUSOL.Infrastructure\ADSOLUSOL.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>
</Project>
